[package]
name = "edrv-hmc5883l"
documentation = "https://docs.rs/edrv-hmc5883l"
description = "HMC5883L 3-axis magnetometer driver for embedded Rust (no_std, I2C)"
keywords = ["hmc5883l", "magnetometer", "compass", "i2c", "no-std"]
readme = "README.md"
version = "0.1.1"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
categories.workspace = true

[dependencies]
embedded-hal.workspace = true
embedded-hal-async.workspace = true

[lints]
workspace = true
