[package]
name = "edrv-sht20"
documentation = "https://docs.rs/edrv-sht20"
description = "SHT20 temperature and humidity sensor driver for embedded Rust (no_std, I2C)"
keywords = ["sht20", "sht2x", "humidity", "temperature", "no-std"]
readme = "README.md"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
categories.workspace = true

[dependencies]
embedded-hal.workspace = true
embedded-hal-async.workspace = true

[features]
default = []
std = []

[lints]
workspace = true
