[package]
name = "edrv-bme680"
documentation = "https://docs.rs/edrv-bme680"
description = "BME680 temperature, humidity, pressure and gas sensor driver for embedded Rust (no_std, I2C)"
keywords = ["bme680", "bme688", "pressure", "gas", "no-std"]
readme = "README.md"
version = "0.1.1"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
categories.workspace = true

[dependencies]
embedded-hal.workspace = true
embedded-hal-async.workspace = true

[lints]
workspace = true
