[package]
name = "edrv-bme280"
documentation = "https://docs.rs/edrv-bme280"
description = "BME280 and BMP280 temperature, pressure and humidity sensor driver for embedded Rust (no_std, I2C)"
keywords = ["bme280", "bmp280", "pressure", "humidity", "no-std"]
readme = "README.md"
version = "0.1.1"
edition.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
categories.workspace = true

[dependencies]
embedded-hal.workspace = true
embedded-hal-async.workspace = true

[features]
default = []
std = []

[lints]
workspace = true
