[package]
name = "edrv-mpu6050"
documentation = "https://docs.rs/edrv-mpu6050"
description = "MPU6050, MPU6000, MPU6500 and MPU9250 6-axis IMU driver for embedded Rust (no_std, I2C)"
keywords = ["mpu6050", "mpu9250", "imu", "gyroscope", "no-std"]
readme = "README.md"
version = "0.1.1"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
categories.workspace = true

[dependencies]
embedded-hal.workspace = true
embedded-hal-async.workspace = true

[features]
default = []
std = []

[lints]
workspace = true
