[package]
name = "edrv-st7735"
documentation = "https://docs.rs/edrv-st7735"
description = "ST7735 TFT display driver for embedded Rust (no_std, SPI)"
keywords = ["st7735", "tft", "display", "spi", "no-std"]
readme = "README.md"
version = "0.1.1"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
categories.workspace = true

[dependencies]
embedded-hal.workspace = true
embedded-hal-async.workspace = true
embedded-graphics-core.workspace = true

[features]
default = []
std = []

[lints]
workspace = true
