[package]
name = "edrv-adxl345"
documentation = "https://docs.rs/edrv-adxl345"
description = "ADXL345 3-axis accelerometer driver for embedded Rust (no_std, I2C)"
keywords = ["adxl345", "accelerometer", "i2c", "no-std"]
readme = "README.md"
version = "0.1.1"
edition.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
categories.workspace = true

[dependencies]
embedded-hal.workspace = true
embedded-hal-async.workspace = true

[lints]
workspace = true
