[package]
name = "edrv-spl06"
documentation = "https://docs.rs/edrv-spl06"
description = "Goertek SPL06-001 and SPL06-007 barometric pressure sensor driver for embedded Rust (no_std, I2C)"
keywords = ["spl06", "spl06-001", "barometer", "pressure", "no-std"]
readme = "README.md"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
categories.workspace = true

[dependencies]
embedded-hal.workspace = true
embedded-hal-async.workspace = true

[lints]
workspace = true
