[package]
name = "edrv-vl53l0x"
documentation = "https://docs.rs/edrv-vl53l0x"
description = "VL53L0X time-of-flight distance sensor driver for embedded Rust (no_std, I2C)"
keywords = ["vl53l0x", "tof", "distance", "lidar", "no-std"]
readme = "README.md"
version = "0.1.1"
edition.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
categories.workspace = true

[dependencies]
embedded-hal.workspace = true
embedded-hal-async.workspace = true

[features]
default = []
std = []

[lints]
workspace = true
