[package]
name = "edrv-mhz19"
documentation = "https://docs.rs/edrv-mhz19"
description = "Driver for the Winsen MH-Z19 / MH-Z19B NDIR CO2 sensor, maintained by the embedded-drivers team"
keywords = ["no-std", "embedded", "embedded-hal-driver", "co2"]
readme = "README.md"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
categories.workspace = true

[dependencies]
embedded-io.workspace = true
embedded-io-async.workspace = true

[features]
default = []
std = []

[lints]
workspace = true
