[package]
name = "edrv-l3g4200d"
documentation = "https://docs.rs/edrv-l3g4200d"
description = "L3G4200D 3-axis gyroscope driver for embedded Rust (no_std, I2C)"
keywords = ["l3g4200d", "gyroscope", "gyro", "i2c", "no-std"]
readme = "README.md"
version = "0.1.1"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
categories.workspace = true

[dependencies]
embedded-hal.workspace = true
embedded-hal-async.workspace = true

[lints]
workspace = true
