[package]
name = "edrv-ltr390uv"
documentation = "https://docs.rs/edrv-ltr390uv"
description = "LTR390UV ambient light and UV sensor driver for embedded Rust (no_std, I2C)"
keywords = ["ltr390uv", "ltr390", "uv", "ambient-light", "no-std"]
readme = "README.md"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
categories.workspace = true

[dependencies]
embedded-hal.workspace = true
embedded-hal-async.workspace = true

[features]
default = []
std = []

[lints]
workspace = true
